########### Data #########################################
dataset_name : "Lorenz"          # "Lorenz" , "Pendulum"
sinerio : "Baseline"             # "Baseline", "Decimation", "Test_Long_Trajectories"
data_gen_flag : False            # True - Generating Dataset. False - Loading Dataset
real_r2 : 0.5                       # observation noise std
#real_q2 : 0.1                     # dynamic noise std

########### Directories ##################################
folder_KNetLatent_model : "./KNetLatent_models" #both models - encoder and KGain
folder_simulations : "./Simulations"
folder_encoder_model : "./Encoder"

########### EKF ##########################################
Evaluate_EKF_flag : False         # True - Evaluate EKF results. False - Load EKF results

########### Architecture #################################
load_KNetLatent_trained : True  # True - loading trained KGain model. False - KGain model start from scratch
flag_Train : False                # True - Training full pipeline. False - Only inference                                  
fix_encoder_flag : False          # True - Encoder is fixed and KGain trainable. False - Encoder is trainable and KGain fixed
prior_flag : True               # True - Encoder with prior. False - Encoder without prior
warm_start_flag : False

############ Hyper Parameters #############################
lr_kalman : 0.001
wd_kalman : 0.01
batch_size : 16
epoches : 300




